### ISSUE TITLE
Unable to open other menu tab

### ISSUE THREAD

**Issue by danieldegroot2** [pietervdvn/MapComplete#2038]
Going to a theme, then into the 'About Mapcomplete'/'Settings' menu in the top left and going to another tab 'About Mapcomplete'/'Settings' (and back by clicking the original tab 'About Mapcomplete'/'Settings' again.) returns the following errors
```
An exception occured undefined Pencil is not defined ReferenceError ReferenceError: Pencil is not defined
    at Array.aJe (UserProfile.svelte:47:51)
    at sJe (UserProfile.svelte:35:21)
    at De (index.mjs:2180:37)
    at new uJe (UserProfile.svelte:22:31)
    at ye (index.mjs:981:12)
    at Array.Or (ToSvelte.svelte:35:39)
    at Object.p (ToSvelte.svelte:34:14)
    at jt (index.mjs:1347:36)
    at at (index.mjs:1307:17)
    at De (index.mjs:2197:9)
ConstructElement @ BaseUIElement.ts:170
(anonymous) @ VariableUIElement.ts:58
addCallbackAndRun @ UIEventSource.ts:529
InnerConstructElement @ VariableUIElement.ts:36
ConstructElement @ BaseUIElement.ts:125
(anonymous) @ ToSvelte.svelte:21
tt @ index.mjs:20
(anonymous) @ index.mjs:2101
at @ index.mjs:1329
Promise.then (async)
Tt @ index.mjs:1258
zt @ index.mjs:2133
(anonymous) @ index.mjs:2171
setSelectedIndex @ TabGroup.svelte:41
ee @ Tab.svelte:74
(anonymous) @ TabbedGroup.svelte:28
setTimeout (async)
r.$$.update @ TabbedGroup.svelte:28
jt @ index.mjs:1343
at @ index.mjs:1307
Promise.then (async)
Tt @ index.mjs:1258
zt @ index.mjs:2133
(anonymous) @ index.mjs:2171
(anonymous) @ If.svelte:14
ping @ UIEventSource.ts:393
setData @ UIEventSource.ts:768
lA @ ThemeViewGUI.svelte:274
(anonymous) @ index.mjs:1189
(anonymous) @ index.mjs:1188
y @ MapControlButton.svelte:24
Show 15 more frames
Show less
```
```
BaseUIElement.ts:178 ReferenceError: Pencil is not defined
    at Array.aJe (UserProfile.svelte:47:51)
    at sJe (UserProfile.svelte:35:21)
    at De (index.mjs:2180:37)
    at new uJe (UserProfile.svelte:22:31)
    at ye (index.mjs:981:12)
    at Array.Or (ToSvelte.svelte:35:39)
    at Object.p (ToSvelte.svelte:34:14)
    at jt (index.mjs:1347:36)
    at at (index.mjs:1307:17)
    at De (index.mjs:2197:9)
ConstructElement @ BaseUIElement.ts:178
(anonymous) @ VariableUIElement.ts:58
addCallbackAndRun @ UIEventSource.ts:529
InnerConstructElement @ VariableUIElement.ts:36
ConstructElement @ BaseUIElement.ts:125
(anonymous) @ ToSvelte.svelte:21
tt @ index.mjs:20
(anonymous) @ index.mjs:2101
at @ index.mjs:1329
Promise.then (async)
Tt @ index.mjs:1258
zt @ index.mjs:2133
(anonymous) @ index.mjs:2171
setSelectedIndex @ TabGroup.svelte:41
ee @ Tab.svelte:74
(anonymous) @ TabbedGroup.svelte:28
setTimeout (async)
r.$$.update @ TabbedGroup.svelte:28
jt @ index.mjs:1343
at @ index.mjs:1307
Promise.then (async)
Tt @ index.mjs:1258
zt @ index.mjs:2133
(anonymous) @ index.mjs:2171
(anonymous) @ If.svelte:14
ping @ UIEventSource.ts:393
setData @ UIEventSource.ts:768
lA @ ThemeViewGUI.svelte:274
(anonymous) @ index.mjs:1189
(anonymous) @ index.mjs:1188
y @ MapControlButton.svelte:24
Show 15 more frames
Show less
```
```
ToSvelte.svelte:34 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'p')
    at Object.p (ToSvelte.svelte:34:14)
    at jt (index.mjs:1347:36)
    at at (index.mjs:1307:17)
```

Upon these errors, the user is stuck within the current tab, unable to click any buttons in the menu.
This can happen while in either tab of the menu.

Theme: Any
Instance: v0.44.8, v0.44.9-dev
Browser: Chrome 126.0.6478.128 / 126.0.6478.183
OS: Windows 10

**Comment by danieldegroot2** [comment]
It seems to be resolved now.

**Comment by danieldegroot2** [comment]
On Edge it seems resolved. Chrome is slowly resolving it seems (I assume it is a caching issue).

**Comment by danieldegroot2** [comment]
After clearing my cache a couple of times, switching back and forth between themes, it has finally updated.
