### ISSUE TITLE
Studio: Cannot read properties of undefined (reading 'actualLanguage')

### ISSUE THREAD

**Issue by danieldegroot2** [pietervdvn/MapComplete#2051]
ref #2038 

Go to studio
Edit existing layer
Go to "Information panel (question and answers)" tab.
Studio breaks with

```
SpecialTranslation.svelte:29 Uncaught (in promise) 
TypeError: Cannot read properties of undefined (reading 'actualLanguage')
    at Ebt (SpecialTranslation.svelte:29:16)
    at De (index.mjs:2165:11)
    at new Rbt (SpecialTranslation.svelte:45:95)
    at Array.Tbt (TagRenderingMapping.svelte:46:57)
    at xbt (TagRenderingMapping.svelte:50:37)
    at De (index.mjs:2180:37)
    at new QZ (TagRenderingMapping.svelte:21:14)
    at jRe (TagRenderingAnswer.svelte:31:86)
    at FRe (TagRenderingAnswer.svelte:32:27)
    at Obt (TagRenderingAnswer.svelte:30:106)
```

Instance: MapComplete 0.44.11(-dev)
Browser: Chrome 127.0.6533.73
OS: Windows 10

**Comment by danieldegroot2** [comment]
Error is slightly different now, but probably still the same.

```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'actualLanguage')
    at Ebt (Add-ce927739.js:1124:4671)
    at De (index.mjs:2165:11)
    at new Rbt (Add-ce927739.js:1124:5560)
    at Array.Tbt (Add-ce927739.js:1124:6280)
    at xbt (Add-ce927739.js:1124:7188)
    at De (index.mjs:2180:37)
    at new QZ (Add-ce927739.js:1124:7874)
    at jRe (Add-ce927739.js:1124:8775)
    at FRe (Add-ce927739.js:1124:8062)
    at Obt (Add-ce927739.js:1124:10483)
```
