### ISSUE TITLE
SyntaxError: C:\Users\gbosch\source\repos\MapComplete\assets\generated\known_layers_and_themes.json: Unexpected token ' in JSON at position 0

### ISSUE THREAD

**Issue by limex** [pietervdvn/MapComplete#308]
Hi, 
run init causes:

> ts-node scripts/generateLayerOverview.ts --no-fail

SyntaxError: C:\Users\gbosch\source\repos\MapComplete\assets\generated\known_layers_and_themes.json: Unexpected token ' in JSON at position 0
    at parse (<anonymous>)
    at Object.Module._extensions..json (internal/modules/cjs/loader.js:1111:22)
    at Module.load (internal/modules/cjs/loader.js:933:32)
    at Function.Module._load (internal/modules/cjs/loader.js:774:14)
    at Module.require (internal/modules/cjs/loader.js:957:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (C:\Users\gbosch\source\repos\MapComplete\Customizations\AllKnownLayers.ts:2:1)
    at Module._compile (internal/modules/cjs/loader.js:1068:30)
    at Module.m._compile (C:\Users\gbosch\source\repos\MapComplete\node_modules\ts-node\src\index.ts:1056:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:1097:10)

**Comment by limex** [comment]
It doesnt fail, but generates 

`'{"layers":[], "themes":[]}' `

**with quotation marks.**

This is also what the error message states.

**Comment by pietervdvn** [comment]
Aha, this is behaviour which is different on linux where those single quotes aren't generated. I've removed the quotes, pull and run again and it should work.
