### ISSUE TITLE
Issue setting up local development

### ISSUE THREAD

**Issue by RayBB** [pietervdvn/MapComplete#616]
Hello,

I am trying to setup the local environment and am getting and error about `license_info.json`

Did I miss a step in setup or is there something else I should do to get this working?

I follow this guide https://github.com/pietervdvn/MapComplete/blob/develop/Docs/Development_deployment.md

Here's a log of what I did:

```
rayberger@Rays-MacBook-Pro Downloads % git clone https://github.com/pietervdvn/MapComplete.git
Cloning into 'MapComplete'...
remote: Enumerating objects: 41720, done.
remote: Counting objects: 100% (2003/2003), done.
remote: Compressing objects: 100% (1388/1388), done.
remote: Total 41720 (delta 1081), reused 1303 (delta 579), pack-reused 39717
Receiving objects: 100% (41720/41720), 340.56 MiB | 25.15 MiB/s, done.
Resolving deltas: 100% (30986/30986), done.
rayberger@Rays-MacBook-Pro Downloads % cd MapComplete 
rayberger@Rays-MacBook-Pro MapComplete % git switch master
Branch 'master' set up to track remote branch 'master' from 'origin'.
Switched to a new branch 'master'
rayberger@Rays-MacBook-Pro MapComplete % git pull
Already up to date.
rayberger@Rays-MacBook-Pro MapComplete % npm install
# removed excessive npm warns here

added 1581 packages, and audited 1582 packages in 12s

197 packages are looking for funding
  run `npm fund` for details

80 vulnerabilities (2 low, 58 moderate, 17 high, 3 critical)

To address issues that do not require attention, run:
  npm audit fix

To address all issues possible (including breaking changes), run:
  npm audit fix --force

Some issues need review, and may require choosing
a different dependency.

Run `npm audit` for details.
rayberger@Rays-MacBook-Pro MapComplete % npm run start

> mapcomplete@0.0.5 start
> npm run start:prepare && npm-run-all --parallel start:parallel:*


> mapcomplete@0.0.5 start:prepare
> ts-node scripts/generateLayerOverview.ts --no-fail && npm run increase-memory


/Users/rayberger/Downloads/MapComplete/node_modules/ts-node/src/index.ts:513
    return new TSError(diagnosticText, diagnosticCodes)
           ^
TSError: ⨯ Unable to compile TypeScript:
scripts/generateLayerOverview.ts:3:27 - error TS2307: Cannot find module '../assets/generated/license_info.json' or its corresponding type declarations.

3 import * as licenses from "../assets/generated/license_info.json"
                            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

    at createTSError (/Users/rayberger/Downloads/MapComplete/node_modules/ts-node/src/index.ts:513:12)
    at reportTSError (/Users/rayberger/Downloads/MapComplete/node_modules/ts-node/src/index.ts:517:19)
    at getOutput (/Users/rayberger/Downloads/MapComplete/node_modules/ts-node/src/index.ts:752:36)
    at Object.compile (/Users/rayberger/Downloads/MapComplete/node_modules/ts-node/src/index.ts:968:32)
    at Module.m._compile (/Users/rayberger/Downloads/MapComplete/node_modules/ts-node/src/index.ts:1056:42)
    at Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Object.require.extensions.<computed> [as .ts] (/Users/rayberger/Downloads/MapComplete/node_modules/ts-node/src/index.ts:1059:12)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
```

**Comment by riQQ** [comment]
You skipped running `npm run init`.

**Comment by RayBB** [comment]
Thanks it's working now. I was just didn't see the `run` in `npm run init` which caused some confusion.
